// <auto-generated />
using CaptureTheIsland.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaptureTheIsland.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251107235149_Install")]
    partial class Install
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaptureTheIsland.Models.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResourceId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            ResourceId = 1,
                            Description = "dCode is the universal site for deciphering coded messages, cheating at word games, solving puzzles, geocaches and treasure hunts, etc.",
                            Link = "https://www.dcode.fr",
                            Name = "dCode"
                        },
                        new
                        {
                            ResourceId = 2,
                            Description = "Cyber Chef is a helpful cryptography resource. This site lets you chain together encoding methods and other tools.",
                            Link = "https://cyberchef.org",
                            Name = "Cyber Chef"
                        },
                        new
                        {
                            ResourceId = 3,
                            Description = "Helpful resource to find information about who owns a domain.",
                            Link = "https://www.whois.com/whois",
                            Name = "Whois Domain Lookup"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
